export const TABLE_RESIZE = 'TABLE_RESIZE';
export const CHANGE_TEXT = 'CHANGE_TEXT';
export const APPLY_STYLE = 'APPLY_STYLE';
export const CHANGE_CURRENT_STYLES= 'CHANGE_CURRENT_STYLES';
export const CHANGE_TITLE= 'CHANGE_TITLE';
